# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simple_forums', '0005_thread_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
