# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_forums', '0007_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='topic',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='simple_forums.Topic'),
            preserve_default=False,
        ),
    ]
