# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_forums', '0008_thread_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default='default'),
            preserve_default=False,
        ),
    ]
