# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simple_forums', '0010_thread_sticky'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='time_last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
