# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_forums', '0011_thread_time_last_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('topic_order',)},
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
