# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-09 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_forums', '0012_auto_20160412_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='time_last_activity',
            field=models.DateTimeField(blank=True),
        ),
    ]
