language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

services:
  - elasticsearch

env:
  matrix:
    - DJANGO="django >=1.8,<1.9"
    - DJANGO="django >=1.9,<1.10"

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="django >=1.9,<1.10"

before_install:
  # pip >= 8 dropped support for python 3.2
  - pip install --upgrade "pip<8.0.0" wheel

# install dependencies
install:
  - pip install "$DJANGO"
  - pip install bleach codecov elasticsearch flake8 markdown pymdown-extensions

# lint before testing
before_script:
  # allow elasticsearch to get setup
  - sleep 10
  - flake8 .

# run tests
script: coverage run --source='.' ./manage.py test

# publish coverage reports
after_success:
  - coverage report
  - codecov

# Only send emails about failures
notifications:
  email:
    on_success: never
    on_failure: always