language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  matrix:
    - DJANGO="django >=1.8,<1.9"
    - DJANGO="django >=1.9,<1.10"

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="django >=1.9,<1.10"

before_install:
  # pip >= 8 dropped support for python 3.2
  - pip install --upgrade "pip<8.0.0" wheel

# install dependencies
install:
  - pip install "$DJANGO"
  - pip install bleach codecov django-admin-sortable factory_boy
  - pip install markdown pymdown-extensions "pytest >= 2.9" pytest-django

# run tests
script: coverage run --source='.' -m pytest

# publish coverage reports
after_success:
  - coverage report
  - codecov

# Only send emails about failures
notifications:
  email:
    on_success: never
    on_failure: always
